#!/usr/local/bin/python3.6
import json
import os
import subprocess
import sys

import boto3

SPACES_REGION='nyc3'
SPACES_BUCKET='nmyk'
NGINX_ROOT='/var/www/html'

content_types = {
    '.css': 'text/css',
    '.js': 'text/javascript'
}

with open('secrets.json') as secrets_file:
    secrets = json.load(secrets_file)

spaces = boto3.client(
    's3',
    region_name=SPACES_REGION,
    endpoint_url=f'https://{SPACES_REGION}.digitaloceanspaces.com',
    aws_access_key_id=secrets['SPACES_KEY'],
    aws_secret_access_key=secrets['SPACES_SECRET']
)


def upload(asset):
    path = f'assets/{asset}'
    _, file_ext = os.path.splitext(path)
    with open(path, 'rb') as asset_file:
        resp = spaces.put_object(
            Bucket=SPACES_BUCKET,
            Key=path,
            Body=asset_file,
            ContentType=content_types.get(file_ext, 'binary/octet-stream'),
            ACL='public-read'
        )
    if not resp['ResponseMetadata']['HTTPStatusCode'] == 200:
        print(f'Could not upload to spaces: {asset}', resp)
        sys.exit(1)
    print(f'❯ {asset}')


def main():
    for asset in os.listdir('assets'):
        upload(asset)
    scp_cmd = f'scp -q index.html root@nmyk.io:{NGINX_ROOT}'.split()
    if subprocess.run(scp_cmd).returncode:
        print('Could not upload to host: index.html')
        sys.exit(1)
    print('❯ index.html')
    print('Done')


if __name__ == '__main__':
    main()
